### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ivanionut** [jordanclark/cfvalid#1]
Hi @jordanclark
are looking for a quick way to integrate forms validation in fw/1.

Where can I find a _mini howto_ to use cfvalid?

Thank you! 
Ivan

**Comment by jordanclark** [comment]
@ivanionut thanks for the question, I do need to provide better documentation.
I've just pushed a new example.cfm in the latest release that shows how simple it is to get started with. I hope that helps, let me know if you have any questions.

**Comment by ivanionut** [comment]
Hi @jordanclark and thanks for the documentation and for the sample script!
